### ISSUE TITLE
Linux build instructions are incomplete

### ISSUE THREAD

**Issue by oconnor663** [mp81ss/badsum#1]
The README says "be sure to add the INCLUDE folder from windows package," but I'm not familiar with fasm myself, so it's not clear to me what that means. I was able to get `make` working with the following:

```bash
wget "https://flatassembler.net/fasmw17327.zip"
unzip fasmw17327.zip INCLUDE/MACRO/STRUCT.INC
sed -i s/%fasm%/./ md5.asm sha1.asm
make
```

Maybe those commands (or something less hacky) could go in the README?

**Comment by mp81ss** [comment]
Extract the linux package to dir /opt/fasm
Download the windows package, open it with winzip and extract the INCLUDE folder to /opt/fasm so that the INCLUDE folder is added to fasm linux package
Then type export fasm=/opt/fasm
Then type make
