### ISSUE TITLE
benchmark results might not be consistent across distros

### ISSUE THREAD

**Issue by oconnor663** [mp81ss/badsum#2]
I'm on Arch Linux myself, and here's what I see from `hyperfine`:

```
❯ head -c 100000000 /dev/urandom > input
❯ hyperfine "md5sum input" "sha1sum input" "./badsum -sha1 input" "./badsum -md5 input"
...
Summary
  'sha1sum input' ran
    1.37 ± 0.01 times faster than 'md5sum input'
    2.10 ± 0.02 times faster than './badsum -md5 input'
    2.28 ± 0.01 times faster than './badsum -sha1 input'
```

The results don't seem to vary much with TurboBoost enabled or disabled.

I think one of the factors here is that the Coreutils package on Arch Linux links against OpenSSL for its crypto implementations. It might be that the results from your README are from a Linux distro that doesn't do that.

**Comment by mp81ss** [comment]
You're right, benchmark vary so much across distro. I updated the benchmark notes, thank you

**Comment by mp81ss** [comment]
You're right, benchmark vary so much across distro. I updated the benchmark notes, thank you
